In [2]:
import var_selection
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
print(dataset)


     Heat  Tricalcium_aluminate  Tricalcium_silicate  \
0    78.5                     7                   26   
1    74.3                     1                   29   
2   104.3                    11                   56   
3    87.6                    11                   31   
4    95.9                     7                   52   
5   109.2                    11                   55   
6   102.7                     3                   71   
7    72.5                     1                   31   
8    93.1                     2                   54   
9   115.9                    21                   47   
10   83.8                     1                   40   
11  113.3                    11                   66   
12  109.4                    10                   68   

    Tetracalcium_alumino_ferrite  Dicalcium_silicate  
0                              6                   6  
1                             15                  52  
2                              8                  

In [16]:
dataset = pd.read_csv('./data/hald_data.csv', delimiter='\t')
X = dataset[['Tricalcium_aluminate','Tricalcium_silicate','Tetracalcium_alumino_ferrite','Dicalcium_silicate']]
y = dataset[['Heat']]
corrMat = X.corr()
print('Covariate sample correlation matrix:\n'+str(corrMat))

Covariate sample correlation matrix:
                              Tricalcium_aluminate  Tricalcium_silicate  \
Tricalcium_aluminate                      1.000000             0.228579   
Tricalcium_silicate                       0.228579             1.000000   
Tetracalcium_alumino_ferrite             -0.824134            -0.139242   
Dicalcium_silicate                       -0.245239            -0.645150   

                              Tetracalcium_alumino_ferrite  Dicalcium_silicate  
Tricalcium_aluminate                             -0.824134           -0.245239  
Tricalcium_silicate                              -0.139242           -0.645150  
Tetracalcium_alumino_ferrite                      1.000000            0.296988  
Dicalcium_silicate                                0.296988            1.000000  


In [17]:
[Evals, Evecs] = np.linalg.eig(corrMat)
print('Eigenvalues of Covariate sample correlation matrix: \n'+str(Evals))

Eigenvalues of Covariate sample correlation matrix: 
[ 2.20088742  1.27454268  0.15083888  0.37373102]


In [18]:
X = np.concatenate([X.as_matrix(), np.ones([X.shape[0],1])], axis = 1)
y = y.as_matrix()

In [19]:
OLS_β = np.dot( np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, y))
OLS_β_std = np.linalg.inv(np.dot(X.T, X))
print('Least squares coefficients: \n' + str(OLS_β[:-1]))
print('Least squares standard error: \n'+str(np.sqrt(np.diag(OLS_β_std[:,:-1]))))

Least squares coefficients: 
[[ 1.69345325]
 [ 0.65952843]
 [ 0.24612004]
 [ 0.00413696]]
Least squares standard error: 
[ 0.08980409  0.02523084  0.08357131  0.02603663]


In [28]:
delta_Heat = 20.
delta_Tricalcium_aluminate = 10.
delta_Tricalcium_silicate = 22.5
delta_Tetracalcium_alumino_ferrite = 8.5
delta_Dicalcium_silicate = 27.

In [29]:
τ_star = delta_Heat / np.array([delta_Tricalcium_aluminate,delta_Tricalcium_silicate,delta_Tetracalcium_alumino_ferrite,delta_Dicalcium_silicate])
print(τ_star)

[ 2.          0.88888889  2.35294118  0.74074074]


In [29]:
E = y - np.dot(X, OLS_β)

In [30]:
np.mean(E)

-1.0555658911051489e-14

In [30]:
β = np.zeros([5,1])
ϵ_squared = 2.5
p = np.concatenate([0.5 * np.ones([4,1]), np.zeros([1,1])])
τ = np.concatenate([np.atleast_2d(τ_star).T, 9 * np.ones([1,1])])
v = 0.01
ν = np.ones([5,1]) * 10e5
λ = np.concatenate([0.1*np.ones([1,1]), 10e10 * np.ones([4,1])])
iterations = 10

In [31]:
τ.shape

(5, 1)

In [34]:
"""
X: numpy.ndarray
y: numpy.ndarray
β: numpy.ndarray
ϵ_squared : scalar
p: iterable
τ: numpy.ndarray
v: scalar
ν: iterable
λ: iterable
iterations: scalar
"""
var_selection.variable_selection(X, y, β, ϵ_squared, p, τ, v, ν, λ, 10)

C:\Users\huang\Anaconda3\lib\site-packages\scipy\stats\_continuous_distns.py:4838: RuntimeWarning: invalid value encountered in log
  self._logdelta = np.log(self._delta)
C:\Users\huang\Anaconda3\lib\site-packages\scipy\stats\_continuous_distns.py:4838: RuntimeWarning: divide by zero encountered in log
  self._logdelta = np.log(self._delta)
C:\Users\huang\Desktop\mcmc_proj7-master\var_selection.py:36: RuntimeWarning: invalid value encountered in multiply
  bf *= sp_norm.cdf((υ - β_bar)/σ_star) - sp_norm.cdf((λ - β_bar)/σ_star)
C:\Users\huang\Desktop\mcmc_proj7-master\var_selection.py:42: RuntimeWarning: invalid value encountered in greater_equal
  if np.random.rand() <= p:


ValueError: Domain error in arguments.

In [33]:
X.shape

(13, 5)